### ISSUE TITLE
error: A hash of at least 15 characters is required

### ISSUE THREAD

**Issue by melvincarvalho** [fiatjaf/branle#2]
## Setup

Running `quasar build` and then `quasar serve -h dist/spa` or `quasar dev`

## Error

This error comes in the browser, on on first use

```
error: A hash of at least 15 characters is required
```

I've tested it in a couple of places and on localhost, also @bumi got the same problem

I'm sure `quasar dev` has worked for me earlier in the week but not now

Will continue to debug ...

**Comment by fiatjaf** [comment]
https://t.me/nostr_protocol/8642

That happens when Identicon receives an undefined input -- because the key generation process failed. It was a bug present at some point in the codebase, but fixed now.

**Comment by pulkitvyas08** [comment]
Still getting this error on `quasar dev` but not with `quasar build`

```
vue-router.esm-bundler.js?f6c4:3295 
A hash of at least 15 characters is required.
```

```
Uncaught (in promise) A hash of at least 15 characters is required.
```

**Comment by fiatjaf** [comment]
Cleanup your local keys and start anew. Does it fix it?

**Comment by pulkitvyas08** [comment]
Still not working

**Comment by melvincarvalho** [comment]
For debugging purposes, the code that triggers it is here:

https://github.com/fiatjaf/branle/blob/176554cddd17aa4fc37ac9bc7d61fe07f31c97a9/src/store/getters.js#L18

It's trying to create an avatar from a pubkey, but the pubkey is not set for some reason.  Normally to do with localStorage I guess

**Comment by melvincarvalho** [comment]
just tried latest master still get the error:

> 'A hash of at least 15 characters is required.'

even after 

```JavaScript 
localStorage.clear()
```

**Comment by fiatjaf** [comment]
I refuse to believe.

**Comment by fiatjaf** [comment]
This is happening.
